CREATE TABLE "promo_definitions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "promo_definitions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" varchar(32) NOT NULL,
	"description" varchar(240) DEFAULT '' NOT NULL,
	"promo_type" varchar(16) NOT NULL,
	"value" integer NOT NULL,
	"minimum_order_minor" bigint DEFAULT 0 NOT NULL,
	"currency" varchar(3) DEFAULT 'RUB' NOT NULL,
	"active_from" timestamp with time zone NOT NULL,
	"active_until" timestamp with time zone,
	"global_usage_limit" integer,
	"per_customer_usage_limit" integer,
	"stacking_policy" varchar(16) DEFAULT 'none' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"is_archived" boolean DEFAULT false NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"created_by_staff_user_id" integer,
	"updated_by_staff_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promo_definitions_code_unique" UNIQUE("code"),
	CONSTRAINT "promo_definitions_created_by_staff_user_id_staff_users_id_fk" FOREIGN KEY ("created_by_staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE set null ON UPDATE cascade,
	CONSTRAINT "promo_definitions_updated_by_staff_user_id_staff_users_id_fk" FOREIGN KEY ("updated_by_staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE set null ON UPDATE cascade,
	CONSTRAINT "promo_definitions_code_format_check" CHECK ("promo_definitions"."code" ~ '^[A-Z0-9][A-Z0-9_-]{0,31}$'),
	CONSTRAINT "promo_definitions_description_length_check" CHECK (length("promo_definitions"."description") <= 240),
	CONSTRAINT "promo_definitions_type_check" CHECK ("promo_definitions"."promo_type" IN ('percent', 'fixed')),
	CONSTRAINT "promo_definitions_value_check" CHECK (("promo_definitions"."promo_type" = 'percent' AND "promo_definitions"."value" BETWEEN 1 AND 100) OR ("promo_definitions"."promo_type" = 'fixed' AND "promo_definitions"."value" BETWEEN 1 AND 1000000000)),
	CONSTRAINT "promo_definitions_minimum_order_check" CHECK ("promo_definitions"."minimum_order_minor" BETWEEN 0 AND 1000000000),
	CONSTRAINT "promo_definitions_currency_check" CHECK ("promo_definitions"."currency" = 'RUB'),
	CONSTRAINT "promo_definitions_active_period_check" CHECK ("promo_definitions"."active_until" IS NULL OR "promo_definitions"."active_until" > "promo_definitions"."active_from"),
	CONSTRAINT "promo_definitions_global_limit_check" CHECK ("promo_definitions"."global_usage_limit" IS NULL OR "promo_definitions"."global_usage_limit" BETWEEN 1 AND 2147483647),
	CONSTRAINT "promo_definitions_customer_limit_check" CHECK ("promo_definitions"."per_customer_usage_limit" IS NULL OR "promo_definitions"."per_customer_usage_limit" BETWEEN 1 AND 2147483647),
	CONSTRAINT "promo_definitions_stacking_policy_check" CHECK ("promo_definitions"."stacking_policy" = 'none'),
	CONSTRAINT "promo_definitions_archive_state_check" CHECK ("promo_definitions"."is_archived" = false OR "promo_definitions"."is_active" = false),
	CONSTRAINT "promo_definitions_version_check" CHECK ("promo_definitions"."version" > 0)
);
--> statement-breakpoint
CREATE INDEX "promo_definitions_status_created_at_idx" ON "promo_definitions" USING btree ("is_archived", "is_active", "created_at", "id");
--> statement-breakpoint
CREATE TABLE "promo_definition_versions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "promo_definition_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"promo_definition_id" integer NOT NULL,
	"version" integer NOT NULL,
	"code" varchar(32) NOT NULL,
	"description" varchar(240) NOT NULL,
	"promo_type" varchar(16) NOT NULL,
	"value" integer NOT NULL,
	"minimum_order_minor" bigint NOT NULL,
	"currency" varchar(3) NOT NULL,
	"active_from" timestamp with time zone NOT NULL,
	"active_until" timestamp with time zone,
	"global_usage_limit" integer,
	"per_customer_usage_limit" integer,
	"stacking_policy" varchar(16) NOT NULL,
	"is_active" boolean NOT NULL,
	"is_archived" boolean NOT NULL,
	"actor_staff_user_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promo_definition_versions_definition_version_unique" UNIQUE("promo_definition_id", "version"),
	CONSTRAINT "promo_definition_versions_promo_definition_id_fk" FOREIGN KEY ("promo_definition_id") REFERENCES "public"."promo_definitions"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "promo_definition_versions_actor_staff_user_id_fk" FOREIGN KEY ("actor_staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE set null ON UPDATE cascade,
	CONSTRAINT "promo_definition_versions_code_format_check" CHECK ("promo_definition_versions"."code" ~ '^[A-Z0-9][A-Z0-9_-]{0,31}$'),
	CONSTRAINT "promo_definition_versions_type_check" CHECK ("promo_definition_versions"."promo_type" IN ('percent', 'fixed')),
	CONSTRAINT "promo_definition_versions_currency_check" CHECK ("promo_definition_versions"."currency" = 'RUB'),
	CONSTRAINT "promo_definition_versions_value_check" CHECK (("promo_definition_versions"."promo_type" = 'percent' AND "promo_definition_versions"."value" BETWEEN 1 AND 100) OR ("promo_definition_versions"."promo_type" = 'fixed' AND "promo_definition_versions"."value" BETWEEN 1 AND 1000000000)),
	CONSTRAINT "promo_definition_versions_period_check" CHECK ("promo_definition_versions"."active_until" IS NULL OR "promo_definition_versions"."active_until" > "promo_definition_versions"."active_from"),
	CONSTRAINT "promo_definition_versions_version_check" CHECK ("promo_definition_versions"."version" > 0)
);
--> statement-breakpoint
CREATE INDEX "promo_definition_versions_definition_created_at_idx" ON "promo_definition_versions" USING btree ("promo_definition_id", "created_at");
--> statement-breakpoint
CREATE TABLE "promo_redemptions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "promo_redemptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"promo_definition_id" integer NOT NULL,
	"customer_id" integer,
	"order_id" integer,
	"source_key" varchar(255) NOT NULL,
	"promo_code" varchar(32) NOT NULL,
	"promo_version" integer NOT NULL,
	"promo_type" varchar(16) NOT NULL,
	"promo_value" integer NOT NULL,
	"discount_minor" bigint NOT NULL,
	"pre_discount_total_minor" bigint NOT NULL,
	"final_total_minor" bigint NOT NULL,
	"currency" varchar(3) NOT NULL,
	"status" varchar(32) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "promo_redemptions_customer_order_definition_unique" UNIQUE("customer_id", "order_id", "promo_definition_id"),
	CONSTRAINT "promo_redemptions_promo_definition_id_fk" FOREIGN KEY ("promo_definition_id") REFERENCES "public"."promo_definitions"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "promo_redemptions_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "promo_redemptions_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "promo_redemptions_source_key_unique" UNIQUE("source_key"),
	CONSTRAINT "promo_redemptions_source_key_not_blank_check" CHECK (length(btrim("promo_redemptions"."source_key")) > 0),
	CONSTRAINT "promo_redemptions_code_format_check" CHECK ("promo_redemptions"."promo_code" ~ '^[A-Z0-9][A-Z0-9_-]{0,31}$'),
	CONSTRAINT "promo_redemptions_type_check" CHECK ("promo_redemptions"."promo_type" IN ('percent', 'fixed')),
	CONSTRAINT "promo_redemptions_value_check" CHECK (("promo_redemptions"."promo_type" = 'percent' AND "promo_redemptions"."promo_value" BETWEEN 1 AND 100) OR ("promo_redemptions"."promo_type" = 'fixed' AND "promo_redemptions"."promo_value" BETWEEN 1 AND 1000000000)),
	CONSTRAINT "promo_redemptions_discount_check" CHECK ("promo_redemptions"."discount_minor" BETWEEN 0 AND "promo_redemptions"."pre_discount_total_minor"),
	CONSTRAINT "promo_redemptions_totals_check" CHECK ("promo_redemptions"."pre_discount_total_minor" >= 0 AND "promo_redemptions"."final_total_minor" >= 0 AND "promo_redemptions"."final_total_minor" + "promo_redemptions"."discount_minor" = "promo_redemptions"."pre_discount_total_minor"),
	CONSTRAINT "promo_redemptions_currency_check" CHECK ("promo_redemptions"."currency" = 'RUB'),
	CONSTRAINT "promo_redemptions_status_check" CHECK ("promo_redemptions"."status" IN ('pending', 'succeeded', 'canceled', 'reconciliation_required'))
);
--> statement-breakpoint
CREATE INDEX "promo_redemptions_definition_status_idx" ON "promo_redemptions" USING btree ("promo_definition_id", "status", "created_at");
--> statement-breakpoint
CREATE INDEX "promo_redemptions_customer_created_at_idx" ON "promo_redemptions" USING btree ("customer_id", "created_at");
