CREATE TABLE "quest_definition_versions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "quest_definition_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quest_definition_id" integer NOT NULL,
	"version" integer NOT NULL,
	"action" varchar(32) NOT NULL,
	"code" varchar(80) NOT NULL,
	"title" varchar(160) NOT NULL,
	"description" varchar(2048) DEFAULT '' NOT NULL,
	"goal" integer NOT NULL,
	"unit" varchar(20) NOT NULL,
	"reward_type" varchar(20) NOT NULL,
	"reward_value" integer NOT NULL,
	"is_visible" boolean NOT NULL,
	"active_from" timestamp with time zone,
	"active_until" timestamp with time zone,
	"sort_order" integer NOT NULL,
	"actor_staff_user_id" integer NOT NULL,
	"request_id" varchar(160) NOT NULL,
	"idempotency_key" varchar(255),
	"payload_fingerprint" varchar(64),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quest_definition_versions_definition_version_unique" UNIQUE("quest_definition_id", "version"),
	CONSTRAINT "quest_definition_versions_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "quest_definition_versions_quest_definition_id_fk" FOREIGN KEY ("quest_definition_id") REFERENCES "public"."quest_definitions"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "quest_definition_versions_actor_staff_user_id_fk" FOREIGN KEY ("actor_staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "quest_definition_versions_action_check" CHECK ("quest_definition_versions"."action" IN ('created', 'updated', 'archived')),
	CONSTRAINT "quest_definition_versions_code_format_check" CHECK ("quest_definition_versions"."code" ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
	CONSTRAINT "quest_definition_versions_title_not_blank_check" CHECK (length(btrim("quest_definition_versions"."title")) > 0),
	CONSTRAINT "quest_definition_versions_goal_check" CHECK ("quest_definition_versions"."goal" BETWEEN 1 AND 2147483647),
	CONSTRAINT "quest_definition_versions_unit_check" CHECK ("quest_definition_versions"."unit" IN ('order', 'minor_units')),
	CONSTRAINT "quest_definition_versions_reward_type_check" CHECK ("quest_definition_versions"."reward_type" IN ('xp', 'coal')),
	CONSTRAINT "quest_definition_versions_reward_value_check" CHECK ("quest_definition_versions"."reward_value" BETWEEN 1 AND 2147483647),
	CONSTRAINT "quest_definition_versions_sort_order_check" CHECK ("quest_definition_versions"."sort_order" >= 0),
	CONSTRAINT "quest_definition_versions_version_check" CHECK ("quest_definition_versions"."version" > 0),
	CONSTRAINT "quest_definition_versions_request_id_check" CHECK (length(btrim("quest_definition_versions"."request_id")) > 0),
	CONSTRAINT "quest_definition_versions_fingerprint_check" CHECK ("quest_definition_versions"."payload_fingerprint" IS NULL OR "quest_definition_versions"."payload_fingerprint" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "quest_definition_versions_period_check" CHECK ("quest_definition_versions"."active_until" IS NULL OR "quest_definition_versions"."active_from" IS NULL OR "quest_definition_versions"."active_until" > "quest_definition_versions"."active_from")
);
--> statement-breakpoint
CREATE INDEX "quest_definition_versions_definition_created_at_idx" ON "quest_definition_versions" USING btree ("quest_definition_id", "created_at");
