CREATE TABLE IF NOT EXISTS "wheel_prize_versions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "wheel_prize_versions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"wheel_prize_id" integer NOT NULL,
	"version" integer NOT NULL,
	"action" varchar(32) NOT NULL,
	"code" varchar(80) NOT NULL,
	"name" varchar(160) NOT NULL,
	"description" varchar(2048) NOT NULL,
	"prize_type" varchar(20) NOT NULL,
	"value" integer NOT NULL,
	"weight" integer NOT NULL,
	"is_visible" boolean NOT NULL,
	"active_from" timestamp with time zone,
	"active_until" timestamp with time zone,
	"sort_order" integer NOT NULL,
	"actor_staff_user_id" integer NOT NULL,
	"request_id" varchar(160) NOT NULL,
	"idempotency_key" varchar(255) NOT NULL,
	"payload_fingerprint" varchar(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "wheel_prize_versions_wheel_prize_id_wheel_prizes_id_fk" FOREIGN KEY ("wheel_prize_id") REFERENCES "public"."wheel_prizes"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "wheel_prize_versions_actor_staff_user_id_staff_users_id_fk" FOREIGN KEY ("actor_staff_user_id") REFERENCES "public"."staff_users"("id") ON DELETE restrict ON UPDATE cascade,
	CONSTRAINT "wheel_prize_versions_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "wheel_prize_versions_prize_version_unique" UNIQUE("wheel_prize_id", "version"),
	CONSTRAINT "wheel_prize_versions_action_check" CHECK ("action" = 'updated'),
	CONSTRAINT "wheel_prize_versions_code_format_check" CHECK ("code" ~ '^[a-z0-9][a-z0-9_-]{0,79}$'),
	CONSTRAINT "wheel_prize_versions_name_not_blank_check" CHECK (length(btrim("name")) > 0),
	CONSTRAINT "wheel_prize_versions_type_check" CHECK ("prize_type" IN ('no_prize', 'coal', 'xp')),
	CONSTRAINT "wheel_prize_versions_value_check" CHECK (("prize_type" = 'no_prize' AND "value" = 0) OR ("prize_type" IN ('coal', 'xp') AND "value" > 0)),
	CONSTRAINT "wheel_prize_versions_weight_check" CHECK ("weight" BETWEEN 0 AND 2147483647),
	CONSTRAINT "wheel_prize_versions_sort_order_check" CHECK ("sort_order" >= 0),
	CONSTRAINT "wheel_prize_versions_version_check" CHECK ("version" > 0),
	CONSTRAINT "wheel_prize_versions_request_id_check" CHECK (length(btrim("request_id")) > 0),
	CONSTRAINT "wheel_prize_versions_fingerprint_check" CHECK ("payload_fingerprint" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "wheel_prize_versions_active_period_check" CHECK ("active_until" IS NULL OR "active_from" IS NULL OR "active_until" > "active_from")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wheel_prize_versions_created_at_idx" ON "wheel_prize_versions" USING btree ("created_at");
